# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-02 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Club Name')),
                ('shortName', models.CharField(blank=True, max_length=200, null=True, verbose_name='Short Name')),
                ('nickName', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nickname')),
                ('footballAPIId', models.IntegerField(blank=True, default=0, null=True, unique=True, verbose_name='Football API Team Id')),
                ('crest', models.FileField(blank=True, null=True, upload_to='crests')),
                ('color', models.CharField(blank=True, max_length=200, null=True, verbose_name='Color')),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footballAPIId', models.IntegerField(blank=True, default=0, null=True, unique=True, verbose_name='Football API Competition Id')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name')),
                ('region', models.CharField(blank=True, max_length=200, null=True, verbose_name='Region')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footballAPIId', models.IntegerField(null=True, unique=True)),
                ('eventType', models.CharField(max_length=200, null=True)),
                ('minute', models.IntegerField(default=0, null=True)),
                ('extraMinute', models.IntegerField(default=0, null=True)),
                ('player', models.CharField(max_length=200, null=True)),
                ('playerFootballAPIId', models.IntegerField(default=0, null=True)),
                ('assist', models.CharField(max_length=200, null=True)),
                ('assistFootballAPIId', models.IntegerField(default=0, null=True)),
                ('result', models.CharField(max_length=50, null=True)),
                ('eventTeamName', models.CharField(max_length=200, null=True)),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matchday.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footballAPIId', models.IntegerField(default=0, verbose_name='Football API Match Id')),
                ('matchTime', models.DateTimeField(blank=True, null=True, verbose_name='Match Time GMT')),
                ('homeClubScore', models.IntegerField(blank=True, null=True, verbose_name='Home Club Score')),
                ('visitorClubScore', models.IntegerField(blank=True, null=True, verbose_name='Visitor Club Score')),
                ('homeClubPenalties', models.IntegerField(blank=True, null=True, verbose_name='Home Club Penalties')),
                ('visitorClubPenalties', models.IntegerField(blank=True, null=True, verbose_name='Visitor Club Penalties')),
                ('timer', models.CharField(blank=True, max_length=10, null=True)),
                ('venue', models.CharField(blank=True, max_length=100, null=True)),
                ('venueCity', models.CharField(blank=True, max_length=100, null=True, verbose_name='Venue City')),
                ('tvDetails', models.CharField(blank=True, max_length=100, null=True, verbose_name='TV Details')),
                ('display', models.BooleanField(default=False, verbose_name='Display Match')),
                ('preMatchDetails', models.CharField(max_length=500, null=True, verbose_name='Pre Match Details')),
                ('inMatchDetails', models.CharField(blank=True, max_length=500, verbose_name='In Match Details')),
                ('postMatchDetails', models.CharField(blank=True, max_length=500, verbose_name='Post Match Details')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchday.Competition', verbose_name='Competition/League')),
                ('homeClub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_homeClubs', to='matchday.Club', verbose_name='Home Club (API Local Club)')),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='MatchStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, null=True, verbose_name='Match Status')),
                ('sortOrder', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1)),
            ],
            options={
                'verbose_name': 'Match Status',
                'verbose_name_plural': 'Match Statuses',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matchday.MatchStatus', verbose_name='Match Status'),
        ),
        migrations.AddField(
            model_name='match',
            name='visitorClub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_visitorClubs', to='matchday.Club', verbose_name='Visitor Club (API Visitor Club)'),
        ),
        migrations.AddField(
            model_name='event',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matchday.Match'),
        ),
    ]
