# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-02 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchday', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchstatus',
            name='descriptions',
            field=models.CharField(max_length=500, null=True, verbose_name='Match Status'),
        ),
    ]
