# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-02 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchday', '0003_auto_20170402_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchstatus',
            name='sortOrder',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1),
        ),
    ]
