# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-02 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchday', '0009_auto_20170802_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='inMatchDetails',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='In Match Details'),
        ),
        migrations.AlterField(
            model_name='match',
            name='postMatchDetails',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Post Match Details'),
        ),
        migrations.AlterField(
            model_name='match',
            name='preMatchDetails',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Pre Match Details'),
        ),
    ]
