# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-02 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchday', '0012_auto_20170802_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='text',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(max_length=50),
        ),
    ]
