# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-04 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchday', '0013_auto_20170802_0419'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextBlurb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
