# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-22 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchday', '0018_remove_match_highlightsurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='highlightsUrl',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Highlights URL'),
        ),
    ]
