# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-07 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchday', '0019_match_highlightsurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='MustReadWatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortCode', models.CharField(max_length=5)),
                ('text', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
                ('mustType', models.CharField(choices=[('read', 'Read'), ('watch', 'Watch')], max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
