# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-07 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchday', '0020_auto_20171007_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mustreadwatch',
            name='shortCode',
        ),
        migrations.AlterField(
            model_name='mustreadwatch',
            name='mustType',
            field=models.CharField(choices=[('read', 'Read'), ('watch', 'Watch')], max_length=256, verbose_name='Type'),
        ),
    ]
